### ISSUE TITLE
wrong of running th run_texture_optimization.lua

### ISSUE THREAD

**Issue by kennylovesfree** [leehomyc/Faster-High-Res-Neural-Inpainting#11]
thank you for providing your code. 
When I run th run_texture_optimization.lua, it shows that it has something wrong of 
init.lua: 724: bad argument #2 to "new"((number has no integer representation))

does anyone encounter the same problem? Thanks

**Comment by leehomyc** [comment]
I don't. Did you solve this?

**Comment by kennylovesfree** [comment]
Yes, it is Lua version problem lol
Do you have original 32 pics which used in inpainting? I want to compare PSNR 
Thanks a lot!

**Comment by leehomyc** [comment]
I believe they are all from ImageNet. If you still want the original image you can email me. By the way I have put up all the images on the project website.
