### ISSUE TITLE
wrong when running "th run_content_network.lua"

### ISSUE THREAD

**Issue by bjrjk** [leehomyc/Faster-High-Res-Neural-Inpainting#12]
This is the stack info:
/root/torch/install/bin/luajit: /root/torch/install/share/lua/5.1/trepl/init
lua:389: module 'cudnn' not found:No LuaRocks module found for cudnn
        no field package.preload['cudnn']
        no file '/root/.luarocks/share/lua/5.1/cudnn.lua'
        no file '/root/.luarocks/share/lua/5.1/cudnn/init.lua'
        no file '/root/torch/install/share/lua/5.1/cudnn.lua'
        no file '/root/torch/install/share/lua/5.1/cudnn/init.lua'
        no file './cudnn.lua'
        no file '/root/torch/install/share/luajit-2.1.0-beta1/cudnn.lua'
        no file '/usr/local/share/lua/5.1/cudnn.lua'
        no file '/usr/local/share/lua/5.1/cudnn/init.lua'
        no file '/root/.luarocks/lib/lua/5.1/cudnn.so'
        no file '/root/torch/install/lib/lua/5.1/cudnn.so'
        no file '/root/torch/install/lib/cudnn.so'
        no file './cudnn.so'
        no file '/usr/local/lib/lua/5.1/cudnn.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'error'
        /root/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'r
quire'
        run_content_network.lua:6: in main chunk
        [C]: in function 'dofile'
        /root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in ma
n chunk
        [C]: at 0x00406670

**Comment by leehomyc** [comment]
Did you install cudnn?

**Comment by torrtuga** [comment]
@leehomyc How to install cudnn?

**Comment by leehomyc** [comment]
Try this: luarocks install cudnn
