### ISSUE TITLE
Error while running commands

### ISSUE THREAD

**Issue by torrtuga** [leehomyc/Faster-High-Res-Neural-Inpainting#17]
I am trying to run the command  : 
`th run_content_network.lua` 

And I am getting an error message : 

`/Users/arqam/torch/install/bin/luajit: /Users/arqam/torch/install/share/lua/5.1/trepl/init.lua:389: module 'cudnn' not found:No LuaRocks module found for cudnn
	no field package.preload['cudnn']
	no file '/Users/arqam/.luarocks/share/lua/5.1/cudnn.lua'
	no file '/Users/arqam/.luarocks/share/lua/5.1/cudnn/init.lua'
	no file '/Users/arqam/torch/install/share/lua/5.1/cudnn.lua'
	no file '/Users/arqam/torch/install/share/lua/5.1/cudnn/init.lua'
	no file './cudnn.lua'
	no file '/Users/arqam/torch/install/share/luajit-2.1.0-beta1/cudnn.lua'
	no file '/usr/local/share/lua/5.1/cudnn.lua'
	no file '/usr/local/share/lua/5.1/cudnn/init.lua'
	no file '/Users/arqam/.luarocks/lib/lua/5.1/cudnn.so'
	no file '/Users/arqam/torch/install/lib/lua/5.1/cudnn.so'
	no file './cudnn.so'
	no file '/usr/local/lib/lua/5.1/cudnn.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	/Users/arqam/torch/install/share/lua/5.1/trepl/init.lua:389: in function 'require'
	run_content_network.lua:6: in main chunk
	[C]: in function 'dofile'
	...rqam/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x0108248a10`

I did as said in the previous step, so what could be the possible reason for this error?

So if I need to install `cudnn` the how to do that, and do we need server GPUs to run as when I google I found that.
I don't have that and want to run the code in my macbook so is it possible anyway that I can do that?

**Comment by leehomyc** [comment]
In the run_content_network.lua, how about change:
opt = {
  gpu=1,
  ...
}
to:
opt = {
 gpu=0,
 ...
}

Let me know if it helps.
