### ISSUE TITLE
I have problems with running the code with input images of 256*256.

### ISSUE THREAD

**Issue by LambdaWill** [leehomyc/Faster-High-Res-Neural-Inpainting#27]
I have several images whose sizes are 256\*256. I don't want to resize it to 512\*512 as they
will get blurry. Then I come to realize that the following code is hard, just specially for 512*512.
```lua
target_image[{{},{117,232},{117,396}}]:copy(target_image[{{},{1,116},{117,396}}])
target_image[{{},{233,280},{117,396}}]:copy(target_image[{{},{69,116},{117,396}}])
target_image[{{},{281,396},{117,396}}]:copy(target_image[{{},{397,512},{117,396}}])
```
Would you please give the corresponding numbers for 256*256.

**Comment by leehomyc** [comment]
Sorry for the late reply (paper deadline).
Are you talking about this:

output[{{},{73,184},{73,184}}]:copy(fake2[{{},{9, 120},{9, 120}}])
