### ISSUE TITLE
What's the meaning of `N(i) is the set of neighboring locations of i `?

### ISSUE THREAD

**Issue by LambdaWill** [leehomyc/Faster-High-Res-Neural-Inpainting#28]
In your paper, 
![_371](https://user-images.githubusercontent.com/26055298/31669400-90f43e22-b387-11e7-9eed-6d4e8e500648.png)
Could you please elaborate it? What's the exact code of the searching region of `N(i)`?

**Comment by leehomyc** [comment]
This is the same with several papers: CNNMRF and Fast Patch-based Style Transfer of Arbitrary Style. The search region is the whole image except for the hole. In practice we fill in the hole with some initialization (like reflection based on the original image) and use the entire image as the search region. If you are talking about the code it is mrf.lua 118-182. (we filter the image with the patch weight and find the patch that gives largest response).
