### ISSUE TITLE
Bilinear Interpolation

### ISSUE THREAD

**Issue by xzq-forever** [leehomyc/Faster-High-Res-Neural-Inpainting#29]
In the paper, you said," Since Context Encoder only works with 128*128 images and when
the input is larger, we directly upsample the 128*128 output to 512*512 using bilinear interpolation."
But when I use bilinear interpolation, I find the image blurring.

**Comment by leehomyc** [comment]
Are you talking about comparison? Yes we failed to train context encoder 256x256 or 512x512 by adding one more layer in generator or discriminator so cannot compare directly. I asked the authors and they say it may need to use patch gan or other techniques. So we thought the best way to compare is to use the output of context encoder 128 and directly upsample it.

**Comment by xzq-forever** [comment]
Can you explain how to do the upsample？

**Comment by leehomyc** [comment]
bilinear (something like imresize)
