### ISSUE TITLE
Which file used for training?

### ISSUE THREAD

**Issue by xuyifeng-nwpu** [leehomyc/Faster-High-Res-Neural-Inpainting#3]
Thank you share your codes.

Can you tell me which lua file   used for training   the dataset.

**Comment by leehomyc** [comment]
I did not include that to train the content network. But it is similar to the Context Encoders. You can use their code to train on ImageNet. (https://people.eecs.berkeley.edu/~pathak/context_encoder/)

**Comment by xuyifeng-nwpu** [comment]
@leehomyc The joint loss function of your paper is differ from that of context_encoder.  Can I directly use the train code(https://people.eecs.berkeley.edu/~pathak/context_encoder/)? 

  Or  should  I modify the training  lua code in the section of joint loss function?
Thanks.

**Comment by leehomyc** [comment]
No, you don't need to. The model for the content constraint is trained on ImageNet using Context Encoders.
