### ISSUE TITLE
How to realize local texture loss

### ISSUE THREAD

**Issue by royal-feng** [leehomyc/Faster-High-Res-Neural-Inpainting#4]
I am amazing about the technology about the local texture loss , when I read your paper ,I try to realize the local texture loss with CNNMRF ,but failed. Could you point it in your code? I will read it carefully.
Do you need more GPU-memory for your code to train than context-encoder?

**Comment by leehomyc** [comment]
The texture loss is in the second step:  th run_texture_optimization.lua. It is similar to CNNMRF. No, we use 12G of GPU-memory to train as well.

**Comment by NerminSalem** [comment]
hi
can i use cpu instead of gpu for th run_content_network.lua

thanks

**Comment by leehomyc** [comment]
> hi
> can i use cpu instead of gpu for th run_content_network.lua
> 
> thanks

Haven't tried. Did you succeed?
