### ISSUE TITLE
why are matrix values being changed here?

### ISSUE THREAD

**Issue by VinayakDubey** [leehomyc/Faster-High-Res-Neural-Inpainting#6]
Hi, I noticed that in run_content_network.lua, these two lines have been used:
```
    output[output:gt(1)]=1
    output[output:lt(-1)]=-1
```

I was wondering what is the reason behind this?

**Comment by MarcoForte** [comment]
That's just to clip the _output_ values to between [-1, 1] for when the images are saved to a file. Otherwise the save to file will scale according to min and max values of _output_, which will result in incorrect color scaling of the image.

**Comment by leehomyc** [comment]
> That's just to clip the output values to between [-1, 1] for when the images are saved to a file. Otherwise the save to file will scale according to min and max values of output, which will result in incorrect color scaling of the image.

Exactly
