### ISSUE TITLE
How to create the the tensor mask?

### ISSUE THREAD

**Issue by NerminSalem** [leehomyc/Faster-High-Res-Neural-Inpainting#8]
Hii, thanks alot for sharing yr work, it s really intresting
I m trying to inpaint other locations in image rather than the centre, but i m stuck in the step of blend as i want to create a tensor mask corresponding to the region i inpianted so can u plz tell me how to create the tensor mask
I appriate yr help, thanks

**Comment by leehomyc** [comment]
I really created it manually (in some drawing software). I did not find a straight-forward way to realize the blending effects.
